version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - '5601:5601'
    links:
      - elasticsearch

  fluentd:
    build: ./fluentd
    links:
      - elasticsearch
    volumes:
      - ./logs:/logs
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf

volumes:
  elastic:
