version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - '5601:5601'
    links:
      - elasticsearch

  fluentd:
    build: ./fluentd
    links:
      - elasticsearch
    volumes:
      - ./logs:/logs
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
