version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  kibana:
    image: kibana:7.0.0
    ports:
      - '5601:5601'
    links:
      - elasticsearch

  fluentd:
    build: ./fluentd
    links:
      - elasticsearch
    volumes:
      - ./logs:/logs
